<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    public function run(): void
    {
        $permissions = [
            ['name' => 'accounting-periods.create', 'display_name' => 'accounting-periods.create', 'module' => 'accounting-periods'],
            ['name' => 'accounting-periods.delete', 'display_name' => 'accounting-periods.delete', 'module' => 'accounting-periods'],
            ['name' => 'accounting-periods.update', 'display_name' => 'accounting-periods.update', 'module' => 'accounting-periods'],
            ['name' => 'accounting-periods.view', 'display_name' => 'accounting-periods.view', 'module' => 'accounting-periods'],
            ['name' => 'announcements.create', 'display_name' => 'announcements.create', 'module' => 'announcements'],
            ['name' => 'announcements.delete', 'display_name' => 'announcements.delete', 'module' => 'announcements'],
            ['name' => 'announcements.update', 'display_name' => 'announcements.update', 'module' => 'announcements'],
            ['name' => 'announcements.view', 'display_name' => 'announcements.view', 'module' => 'announcements'],
            ['name' => 'blocks.create', 'display_name' => 'blocks.create', 'module' => 'blocks'],
            ['name' => 'blocks.delete', 'display_name' => 'blocks.delete', 'module' => 'blocks'],
            ['name' => 'blocks.update', 'display_name' => 'blocks.update', 'module' => 'blocks'],
            ['name' => 'blocks.view', 'display_name' => 'blocks.view', 'module' => 'blocks'],
            ['name' => 'building-subscriptions.create', 'display_name' => 'building-subscriptions.create', 'module' => 'building-subscriptions'],
            ['name' => 'building-subscriptions.delete', 'display_name' => 'building-subscriptions.delete', 'module' => 'building-subscriptions'],
            ['name' => 'building-subscriptions.update', 'display_name' => 'building-subscriptions.update', 'module' => 'building-subscriptions'],
            ['name' => 'building-subscriptions.view', 'display_name' => 'building-subscriptions.view', 'module' => 'building-subscriptions'],
            ['name' => 'buildings.create', 'display_name' => 'buildings.create', 'module' => 'buildings'],
            ['name' => 'buildings.delete', 'display_name' => 'buildings.delete', 'module' => 'buildings'],
            ['name' => 'buildings.update', 'display_name' => 'buildings.update', 'module' => 'buildings'],
            ['name' => 'buildings.view', 'display_name' => 'buildings.view', 'module' => 'buildings'],
            ['name' => 'charge-formulas.create', 'display_name' => 'charge-formulas.create', 'module' => 'charge-formulas'],
            ['name' => 'charge-formulas.delete', 'display_name' => 'charge-formulas.delete', 'module' => 'charge-formulas'],
            ['name' => 'charge-formulas.update', 'display_name' => 'charge-formulas.update', 'module' => 'charge-formulas'],
            ['name' => 'charge-formulas.view', 'display_name' => 'charge-formulas.view', 'module' => 'charge-formulas'],
            ['name' => 'charge-periods.create', 'display_name' => 'charge-periods.create', 'module' => 'charge-periods'],
            ['name' => 'charge-periods.delete', 'display_name' => 'charge-periods.delete', 'module' => 'charge-periods'],
            ['name' => 'charge-periods.update', 'display_name' => 'charge-periods.update', 'module' => 'charge-periods'],
            ['name' => 'charge-periods.view', 'display_name' => 'charge-periods.view', 'module' => 'charge-periods'],
            ['name' => 'complexes.create', 'display_name' => 'complexes.create', 'module' => 'complexes'],
            ['name' => 'complexes.delete', 'display_name' => 'complexes.delete', 'module' => 'complexes'],
            ['name' => 'complexes.update', 'display_name' => 'complexes.update', 'module' => 'complexes'],
            ['name' => 'complexes.view', 'display_name' => 'complexes.view', 'module' => 'complexes'],
            ['name' => 'documents.create', 'display_name' => 'documents.create', 'module' => 'documents'],
            ['name' => 'documents.delete', 'display_name' => 'documents.delete', 'module' => 'documents'],
            ['name' => 'documents.update', 'display_name' => 'documents.update', 'module' => 'documents'],
            ['name' => 'documents.view', 'display_name' => 'documents.view', 'module' => 'documents'],
            ['name' => 'expenses.create', 'display_name' => 'expenses.create', 'module' => 'expenses'],
            ['name' => 'expenses.delete', 'display_name' => 'expenses.delete', 'module' => 'expenses'],
            ['name' => 'expenses.update', 'display_name' => 'expenses.update', 'module' => 'expenses'],
            ['name' => 'expenses.view', 'display_name' => 'expenses.view', 'module' => 'expenses'],
            ['name' => 'facilities.create', 'display_name' => 'facilities.create', 'module' => 'facilities'],
            ['name' => 'facilities.delete', 'display_name' => 'facilities.delete', 'module' => 'facilities'],
            ['name' => 'facilities.update', 'display_name' => 'facilities.update', 'module' => 'facilities'],
            ['name' => 'facilities.view', 'display_name' => 'facilities.view', 'module' => 'facilities'],
            ['name' => 'facility-reservations.approve', 'display_name' => 'facility-reservations.approve', 'module' => 'facility-reservations'],
            ['name' => 'facility-reservations.cancel', 'display_name' => 'facility-reservations.cancel', 'module' => 'facility-reservations'],
            ['name' => 'facility-reservations.create', 'display_name' => 'facility-reservations.create', 'module' => 'facility-reservations'],
            ['name' => 'facility-reservations.delete', 'display_name' => 'facility-reservations.delete', 'module' => 'facility-reservations'],
            ['name' => 'facility-reservations.update', 'display_name' => 'facility-reservations.update', 'module' => 'facility-reservations'],
            ['name' => 'facility-reservations.view', 'display_name' => 'facility-reservations.view', 'module' => 'facility-reservations'],
            ['name' => 'files.create', 'display_name' => 'files.create', 'module' => 'files'],
            ['name' => 'files.delete', 'display_name' => 'files.delete', 'module' => 'files'],
            ['name' => 'files.update', 'display_name' => 'files.update', 'module' => 'files'],
            ['name' => 'files.view', 'display_name' => 'files.view', 'module' => 'files'],
            ['name' => 'financial-accounts.create', 'display_name' => 'financial-accounts.create', 'module' => 'financial-accounts'],
            ['name' => 'financial-accounts.delete', 'display_name' => 'financial-accounts.delete', 'module' => 'financial-accounts'],
            ['name' => 'financial-accounts.update', 'display_name' => 'financial-accounts.update', 'module' => 'financial-accounts'],
            ['name' => 'financial-accounts.view', 'display_name' => 'financial-accounts.view', 'module' => 'financial-accounts'],
            ['name' => 'financial-categories.create', 'display_name' => 'financial-categories.create', 'module' => 'financial-categories'],
            ['name' => 'financial-categories.delete', 'display_name' => 'financial-categories.delete', 'module' => 'financial-categories'],
            ['name' => 'financial-categories.update', 'display_name' => 'financial-categories.update', 'module' => 'financial-categories'],
            ['name' => 'financial-categories.view', 'display_name' => 'financial-categories.view', 'module' => 'financial-categories'],
            ['name' => 'financial-reconciliations.create', 'display_name' => 'financial-reconciliations.create', 'module' => 'financial-reconciliations'],
            ['name' => 'financial-reconciliations.delete', 'display_name' => 'financial-reconciliations.delete', 'module' => 'financial-reconciliations'],
            ['name' => 'financial-reconciliations.update', 'display_name' => 'financial-reconciliations.update', 'module' => 'financial-reconciliations'],
            ['name' => 'financial-reconciliations.view', 'display_name' => 'financial-reconciliations.view', 'module' => 'financial-reconciliations'],
            ['name' => 'floors.create', 'display_name' => 'floors.create', 'module' => 'floors'],
            ['name' => 'floors.delete', 'display_name' => 'floors.delete', 'module' => 'floors'],
            ['name' => 'floors.update', 'display_name' => 'floors.update', 'module' => 'floors'],
            ['name' => 'floors.view', 'display_name' => 'floors.view', 'module' => 'floors'],
            ['name' => 'funds.create', 'display_name' => 'funds.create', 'module' => 'funds'],
            ['name' => 'funds.delete', 'display_name' => 'funds.delete', 'module' => 'funds'],
            ['name' => 'funds.update', 'display_name' => 'funds.update', 'module' => 'funds'],
            ['name' => 'funds.view', 'display_name' => 'funds.view', 'module' => 'funds'],
            ['name' => 'generated-reports.create', 'display_name' => 'generated-reports.create', 'module' => 'generated-reports'],
            ['name' => 'generated-reports.delete', 'display_name' => 'generated-reports.delete', 'module' => 'generated-reports'],
            ['name' => 'generated-reports.update', 'display_name' => 'generated-reports.update', 'module' => 'generated-reports'],
            ['name' => 'generated-reports.view', 'display_name' => 'generated-reports.view', 'module' => 'generated-reports'],
            ['name' => 'guest-visits.create', 'display_name' => 'guest-visits.create', 'module' => 'guest-visits'],
            ['name' => 'guest-visits.delete', 'display_name' => 'guest-visits.delete', 'module' => 'guest-visits'],
            ['name' => 'guest-visits.update', 'display_name' => 'guest-visits.update', 'module' => 'guest-visits'],
            ['name' => 'guest-visits.view', 'display_name' => 'guest-visits.view', 'module' => 'guest-visits'],
            ['name' => 'guests.create', 'display_name' => 'guests.create', 'module' => 'guests'],
            ['name' => 'guests.delete', 'display_name' => 'guests.delete', 'module' => 'guests'],
            ['name' => 'guests.update', 'display_name' => 'guests.update', 'module' => 'guests'],
            ['name' => 'guests.view', 'display_name' => 'guests.view', 'module' => 'guests'],
            ['name' => 'incomes.create', 'display_name' => 'incomes.create', 'module' => 'incomes'],
            ['name' => 'incomes.delete', 'display_name' => 'incomes.delete', 'module' => 'incomes'],
            ['name' => 'incomes.update', 'display_name' => 'incomes.update', 'module' => 'incomes'],
            ['name' => 'incomes.view', 'display_name' => 'incomes.view', 'module' => 'incomes'],
            ['name' => 'invoices.adjust', 'display_name' => 'invoices.adjust', 'module' => 'invoices'],
            ['name' => 'invoices.create', 'display_name' => 'invoices.create', 'module' => 'invoices'],
            ['name' => 'invoices.delete', 'display_name' => 'invoices.delete', 'module' => 'invoices'],
            ['name' => 'invoices.issue', 'display_name' => 'invoices.issue', 'module' => 'invoices'],
            ['name' => 'invoices.update', 'display_name' => 'invoices.update', 'module' => 'invoices'],
            ['name' => 'invoices.view', 'display_name' => 'invoices.view', 'module' => 'invoices'],
            ['name' => 'loyalty-rewards.create', 'display_name' => 'loyalty-rewards.create', 'module' => 'loyalty-rewards'],
            ['name' => 'loyalty-rewards.delete', 'display_name' => 'loyalty-rewards.delete', 'module' => 'loyalty-rewards'],
            ['name' => 'loyalty-rewards.update', 'display_name' => 'loyalty-rewards.update', 'module' => 'loyalty-rewards'],
            ['name' => 'loyalty-rewards.view', 'display_name' => 'loyalty-rewards.view', 'module' => 'loyalty-rewards'],
            ['name' => 'meeting-minutes.create', 'display_name' => 'meeting-minutes.create', 'module' => 'meeting-minutes'],
            ['name' => 'meeting-minutes.delete', 'display_name' => 'meeting-minutes.delete', 'module' => 'meeting-minutes'],
            ['name' => 'meeting-minutes.update', 'display_name' => 'meeting-minutes.update', 'module' => 'meeting-minutes'],
            ['name' => 'meeting-minutes.view', 'display_name' => 'meeting-minutes.view', 'module' => 'meeting-minutes'],
            ['name' => 'parking-spaces.create', 'display_name' => 'parking-spaces.create', 'module' => 'parking-spaces'],
            ['name' => 'parking-spaces.delete', 'display_name' => 'parking-spaces.delete', 'module' => 'parking-spaces'],
            ['name' => 'parking-spaces.update', 'display_name' => 'parking-spaces.update', 'module' => 'parking-spaces'],
            ['name' => 'parking-spaces.view', 'display_name' => 'parking-spaces.view', 'module' => 'parking-spaces'],
            ['name' => 'payments.create', 'display_name' => 'payments.create', 'module' => 'payments'],
            ['name' => 'payments.delete', 'display_name' => 'payments.delete', 'module' => 'payments'],
            ['name' => 'payments.refund', 'display_name' => 'payments.refund', 'module' => 'payments'],
            ['name' => 'payments.update', 'display_name' => 'payments.update', 'module' => 'payments'],
            ['name' => 'payments.verify', 'display_name' => 'payments.verify', 'module' => 'payments'],
            ['name' => 'payments.view', 'display_name' => 'payments.view', 'module' => 'payments'],
            ['name' => 'plans.create', 'display_name' => 'plans.create', 'module' => 'plans'],
            ['name' => 'plans.delete', 'display_name' => 'plans.delete', 'module' => 'plans'],
            ['name' => 'plans.update', 'display_name' => 'plans.update', 'module' => 'plans'],
            ['name' => 'plans.view', 'display_name' => 'plans.view', 'module' => 'plans'],
            ['name' => 'reports.create', 'display_name' => 'reports.create', 'module' => 'reports'],
            ['name' => 'reports.delete', 'display_name' => 'reports.delete', 'module' => 'reports'],
            ['name' => 'reports.update', 'display_name' => 'reports.update', 'module' => 'reports'],
            ['name' => 'reports.view', 'display_name' => 'reports.view', 'module' => 'reports'],
            ['name' => 'service-requests.create', 'display_name' => 'service-requests.create', 'module' => 'service-requests'],
            ['name' => 'service-requests.delete', 'display_name' => 'service-requests.delete', 'module' => 'service-requests'],
            ['name' => 'service-requests.update', 'display_name' => 'service-requests.update', 'module' => 'service-requests'],
            ['name' => 'service-requests.view', 'display_name' => 'service-requests.view', 'module' => 'service-requests'],
            ['name' => 'storage-units.create', 'display_name' => 'storage-units.create', 'module' => 'storage-units'],
            ['name' => 'storage-units.delete', 'display_name' => 'storage-units.delete', 'module' => 'storage-units'],
            ['name' => 'storage-units.update', 'display_name' => 'storage-units.update', 'module' => 'storage-units'],
            ['name' => 'storage-units.view', 'display_name' => 'storage-units.view', 'module' => 'storage-units'],
            ['name' => 'support-tickets.create', 'display_name' => 'support-tickets.create', 'module' => 'support-tickets'],
            ['name' => 'support-tickets.delete', 'display_name' => 'support-tickets.delete', 'module' => 'support-tickets'],
            ['name' => 'support-tickets.update', 'display_name' => 'support-tickets.update', 'module' => 'support-tickets'],
            ['name' => 'support-tickets.view', 'display_name' => 'support-tickets.view', 'module' => 'support-tickets'],
            ['name' => 'system-settings.create', 'display_name' => 'system-settings.create', 'module' => 'system-settings'],
            ['name' => 'system-settings.delete', 'display_name' => 'system-settings.delete', 'module' => 'system-settings'],
            ['name' => 'system-settings.update', 'display_name' => 'system-settings.update', 'module' => 'system-settings'],
            ['name' => 'system-settings.view', 'display_name' => 'system-settings.view', 'module' => 'system-settings'],
            ['name' => 'unit-invitations.create', 'display_name' => 'unit-invitations.create', 'module' => 'unit-invitations'],
            ['name' => 'unit-invitations.delete', 'display_name' => 'unit-invitations.delete', 'module' => 'unit-invitations'],
            ['name' => 'unit-invitations.update', 'display_name' => 'unit-invitations.update', 'module' => 'unit-invitations'],
            ['name' => 'unit-invitations.view', 'display_name' => 'unit-invitations.view', 'module' => 'unit-invitations'],
            ['name' => 'unit-occupancies.create', 'display_name' => 'unit-occupancies.create', 'module' => 'unit-occupancies'],
            ['name' => 'unit-occupancies.delete', 'display_name' => 'unit-occupancies.delete', 'module' => 'unit-occupancies'],
            ['name' => 'unit-occupancies.update', 'display_name' => 'unit-occupancies.update', 'module' => 'unit-occupancies'],
            ['name' => 'unit-occupancies.view', 'display_name' => 'unit-occupancies.view', 'module' => 'unit-occupancies'],
            ['name' => 'unit-ownerships.create', 'display_name' => 'unit-ownerships.create', 'module' => 'unit-ownerships'],
            ['name' => 'unit-ownerships.delete', 'display_name' => 'unit-ownerships.delete', 'module' => 'unit-ownerships'],
            ['name' => 'unit-ownerships.update', 'display_name' => 'unit-ownerships.update', 'module' => 'unit-ownerships'],
            ['name' => 'unit-ownerships.view', 'display_name' => 'unit-ownerships.view', 'module' => 'unit-ownerships'],
            ['name' => 'units.create', 'display_name' => 'units.create', 'module' => 'units'],
            ['name' => 'units.delete', 'display_name' => 'units.delete', 'module' => 'units'],
            ['name' => 'units.update', 'display_name' => 'units.update', 'module' => 'units'],
            ['name' => 'units.view', 'display_name' => 'units.view', 'module' => 'units'],
            ['name' => 'users.create', 'display_name' => 'users.create', 'module' => 'users'],
            ['name' => 'users.delete', 'display_name' => 'users.delete', 'module' => 'users'],
            ['name' => 'users.update', 'display_name' => 'users.update', 'module' => 'users'],
            ['name' => 'users.view', 'display_name' => 'users.view', 'module' => 'users'],
        ];

        foreach ($permissions as $permission) {
            Permission::query()->updateOrCreate(
                ['name' => $permission['name']],
                $permission,
            );
        }
    }
}
